var ActionTypes = {
  REDIS_TRACES_RECEIVED: 'REDIS_TRACES_RECEIVED',
  REDIS_NEW_TRACE: 'REDIS_NEW_TRACE',
  REDIS_TRACE_META_RECEIVED: 'REDIS_TRACE_META_RECEIVED',
  REDIS_TRACE_RECEIVED: 'REDIS_TRACE_RECEIVED'
};

module.exports = ActionTypes;
